# minimal language just includes git, docker, python, ...
language: minimal

services:
  - docker

before_script:
  - docker build -t jupyter-test .

script:
  - docker run --rm jupyter-test jupyter nbconvert --to notebook --execute /AoC\ 2018.ipynb
